version: '3'
services:
  redis:
    image: 'redis/redis-stack-server:latest'
    container_name: 'redis-container'
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  redis-data:
